version: '2'

services:
    db_ts:
        build: docker/mysql
        volumes:
            - data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_PORT}:3306
        expose:
            - ${MYSQL_PORT}
            - 3306

    ts:
        build: docker/php7-fpm
        env_file: .env
        depends_on:
          - db_ts
        links:
          - db_ts
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/${PROJECT_NAME}:cached
            - ${SYMFONY_APP_PATH}/var/logs:/var/www/${PROJECT_NAME}/var/logs:cached

    nginx_ts:
        build: docker/nginx
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
        volumes_from:
            - ts

volumes:
    data:
